config/routes.rb
Fora::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :dashboard
  root :to => 'home#index'
  resources :boards
  resources :posts
  resources :after_register
  resources :follows
  resources :comments
  resources :posts do
    member do
      post :vote_up
      post :star
      post :unstar
      post :is_star
      post :stars_for
    end
  end
  resources :boards do
    member do
      post :follow_up
      post :follow_down
      post :is_following_up
      post :trending
      get  :trending
      post :new_thread_list
      get  :new_thread_list
      post :popular
      get  :popular
      post :starred
      get  :starred
    end
  end
  resources :replies
  resources :stars

end

app/models/board.rb
class Board < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :posts
  belongs_to :user

 def is_following_up(params, currentUser)
  @found = Follow.find(:all, :conditions => { :user_id => currentUser, :board_id => params, :status => 1 })
   if @found.any?
    true
   else
    false
   end
 end


 def board_member_amount(params)
  @found = Follow.where(:board_id => params, :status => 1).count
 end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
 
 before_filter :authenticate_user!

  def index
    @boards = Board.all
  end

  def show
  	@board = Board.find(params[:id])

  	@post = Post.new
	  @post.board_id = @board.id

    @is_following_up = is_following_up(params[:id])
    @board_members = board_member_amount(params[:id])   
  end

  def new
  	@board = Board.new
  end

  def create
  	@board = Board.new
    @board.user_id = current_user.id
  	@board.title = params[:board][:title]
  	@board.description = params[:board][:description]
    if @board.save

      # ------ Auto Follow 
      @follow = Follow.new
      @follow.user_id = current_user.id
      @follow.board_id = @board.id
      @follow.status = 1

      if @follow.save
        flash[:message] = "Board '#{@board.title}' created!"
      	redirect_to board_path(@board)
      end
    end
  end


  def destroy
    @board = Board.find(params[:id])
    if @board.destroy
      flash[:message] = "Board '#{@board.title}' has been destroyed!"
      redirect_to boards_path
    end
  end

  def edit
    @board = Board.find(params[:id])
  end


  def update
  #raise params.inspect # We use it to debug what's coming from the form (view)
    @board = Board.find(params[:id])
    @board.title = params[:board][:title]
    @board.description = params[:board][:description]
    if @board.save
      flash[:message] = "Board '#{@board.title}' Updated!"
      redirect_to board_path(@board)
    end
  end 

  def list
    @boardsList = Board.all
    
    render 'list'
  end

  def topic_info
    @topic = Board.find(params[:id])
  end

  def follow_up
    #raise params.inspect # We use it to debug what's coming from the form (view)
    @board = Board.find(params[:id])
    @found = Follow.find(:all, :conditions => { :user_id => current_user.id, :board_id => params[:id] })
    if @found.any?
      if @found[0].status == 0
        #update follow status to 1
        @found[0].status = 1
        if @found[0].save
          flash[:message] = "Sweet! You are following '#{@board.title}' again !"
        end
      else
        flash[:message] = "You are already following '#{@board.title}'  !"
      end  
      redirect_to board_path(@board)
    else
      #create a new follow
      @follow = Follow.new
      @follow.user_id = current_user.id
      @follow.board_id = params[:id]
      @follow.status = 1
      if @follow.save
        flash[:message] = "Now you are following '#{@board.title}' ;) !"
        redirect_to board_path(@board)
      end
    end
  end


  def follow_down
    #Follow down 'will not' delete the 'follow', it will just change the status (from 1 to 0)
    @board = Board.find(params[:id])
    @found = Follow.find(:all, :conditions => { :user_id => current_user.id, :board_id => params[:id] })
    if @found.any?
      @found[0].status = 0
      @found[0].save
      flash[:message] = "You just left '#{@board.title}'  !"
      redirect_to board_path(@board)
    else
      flash[:message] = "Oops! You are NOT following '#{@board.title}' !"
      redirect_to board_path(@board)
    end
  end

  def is_following_up(params)
    @found = Follow.find(:all, :conditions => { :user_id => current_user.id, :board_id => params, :status => 1 })
    if @found.any?
      true
    else
      false
    end
  end


  def board_member_amount(params)
    @found = Follow.where(:board_id => params, :status => 1).count
  end


  def trending
    #just for MySQL
    #@trending = Post.tally.where('board_id = ?', params[:id]).having('vote_count < 10')
    #For PostgreSQL
    @trending = Post.tally.where('board_id = ?', params[:id]).having('COUNT(votes.id) < 10')
    @board = Board.find(params[:id])
    @is_following_up = is_following_up(params[:id])
    @board_members = board_member_amount(params[:id])
    render 'trending'
  end


  def new_thread_list
    @thread = Post.find(:all, :conditions => {:board_id => params[:id]}, :order => "created_at DESC")
    
    @is_following_up = is_following_up(params[:id])
    @board_members = board_member_amount(params[:id])
    render 'new_thread_list'
  end
  
  def popular
    postsOnBoard = Post.find(:all, :select => 'id',:conditions => {:board_id => params[:id]}).map(&:id)
    @commentAmountPerPost = Comment.count(:all,:conditions => ['post_id in (?)', postsOnBoard], :group => 'post_id', :order => 'count_all DESC')
    mostCommentedPosts = Comment.find(
    :all, 
    :select => 'count(*) count, post_id', 
    :group => 'post_id', 
    :conditions => ['post_id in (?)', postsOnBoard], 
    :order => 'count DESC').map(&:post_id)
    @popular = Post.find(:all,:conditions => ['id in (?)', mostCommentedPosts], :order => 'created_at')

    
    @board = Board.find(params[:id])
    @is_following_up = is_following_up(params[:id])
    @board_members = board_member_amount(params[:id])
    render 'popular'
  end

  def starred
    postsOnBoard = Post.find(:all, :select => 'id',:conditions => {:board_id => params[:id]}).map(&:id)
    @starredAmountPerPost = Star.count(:all,:conditions => ['post_id in (?)', postsOnBoard], :group => 'post_id', :order => 'count_all DESC')
   
    starredPosts = Star.find(
    :all, 
    :select => 'post_id', 
    :group => 'post_id', 
    :conditions => ['post_id in (?)', postsOnBoard], 
    :order => 'post_id DESC').map(&:post_id)
    @starred = Post.find(:all,:conditions => ['id in (?)', starredPosts], :order => 'created_at')

    @board = Board.find(params[:id])
    @is_following_up = is_following_up(params[:id])
    @board_members = board_member_amount(params[:id])
    render 'starred'
  end

end

app/helpers/boards_helper.rb
module BoardsHelper

 def is_following_up(params)
  @found = Follow.find(:all, :conditions => { :user_id => current_user.id, :board_id => params, :status => 1 })
   if @found.any?
    true
   else
    false
   end
 end


 def board_member_amount(params)
  @found = Follow.where(:board_id => params, :status => 1).count
 end

end

app/views/boards/_follow_board_list.html.erb
<ul>
 
<% if !@followedByUser.nil? %>
	
 <% @followedByUser.each do |follow| %>

  <li>
   <% board = Board.find(follow.board_id) %>
   <%= link_to '#'+board.title, board_path(board) %> | <%= board_member_amount(board.id) %> Members
   
  </li> 

 <% end %>
<% end %>

</ul>

app/views/boards/_last_board.html.erb
<ul>
 <% @boardsListLast.each do |board| %>

  <li>
  
   <%= link_to '#'+board.title, board_path(board) %> | <%= board_member_amount(board.id) %> Members
   
  </li> 

 <% end %>

</ul>

app/views/boards/_list.html.erb
<ul>
 <% @boardsList.each do |board| %>

  <li>
   <%= link_to '#'+board.title, board_path(board) %>
  </li> 

 <% end %>

</ul>

app/views/boards/_post.html.erb
	<li>
		

		<%= link_to(vote_up_post_path(post), :method => :post, :class => "upVote") do %>
			&#9650;<br />
			<span class="upVoteBg"><%=post.votes_for%></span>
		<% end %>


		<%= link_to(star_post_path(post), :method => :post, :class => "upVote") do %>
							&#9650;<br />
							<span class="upVoteBg"><%= Post.find(post.id).stars.count %></span>
		<% end %>

		<%= link_to post, :class => "postLink" do %>

    		
			<span class="left"><span class="title"><%= post.title %></span><span class="floatL"><strong>Replies:</strong> (<%= Post.find(post.id).comments.count %>)</span><span class="floatL"><strong>Last update:</strong> designblooz - <% from_time = Time.now %><%= distance_of_time_in_words(post.created_at, from_time) %> ago</span></span>
			<span class="right"></span>
			<span class="clear"></span>
  		<% end %>

	</li>

app/views/boards/_post_form.erb
<h3>New Thread</h3>
<a href="#" class="newThreadClose">X</a>
<%= form_for @post do |f| %>
  <%= f.hidden_field :board_id %>
  <p>
    <%= f.hidden_field :author_name, :value => current_user.username %>
  </p>
  <p>
    <div class="postEditor" style="background-color:#eee;">
       <%= f.text_field :title, :class => "textInput", :placeholder => "Title" %>
       <%= f.text_area :body, :id => "markItUp" %>
      <button class="btn floatR">Submit</button>      
    </div>    
  </p>
<% end %>

app/views/boards/_topic_info.html.erb
<div class="topicInfo">
	<ul>
	  <li><h3>#<%= @board.title %></h3></li>
	  <li><h5> <%= @board_members %> Members</h5></li>
	  <% if @board.user_id == current_user.id %>
	  <li class="edit_delete">
	  	<%= link_to "Edit", edit_board_path(@board), :class => "btn" %>
	  	
	  </li>
	  <% end %>

	  <li class="follow">
	  	<% if @is_following_up %>
	  		<%= link_to "Unfollow", follow_down_board_path(@board), :method => :post,:class => "btn btn-white" %>
	  	<% else %>
	  		<%= link_to "Follow Up", follow_up_board_path(@board), :method => :post,:class => "btn btn-white" %>
	  	<% end %>
	  </li>
	</ul>
</div>	
<!-- new thread -->
<div class="newThread">
	<button id="newThreadBtn" class="btn btn-big btn-white">+ New Thread</button>
</div>
<div class="clear"></div>

app/views/boards/edit.html.erb
<h1>Edit an Board</h1>

<%= form_for(@board) do |f| %>
  <ul>
  <% @board.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/boards/index.html.erb
<h1> All Boards </h1>

<ul>
 Signed in as: <%= current_user.username %>
 <% @boards.each do |board| %>

  <li>
   <%= link_to board.title, board_path(board) %>
  </li>

 <% end %>

</ul>

app/views/boards/new.html.erb
<h1>Create a New Board</h1>

<%= form_for(@board) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/boards/new_thread_list.html.erb
<h2> New threads</h2>

<ul>
 <% @thread.each do |post| %>

   <% if !post.title.nil? %>
   	<li>
   		<%= link_to '#'+post.title, post_path(post) %> |
   		<% from_time = Time.now %><%= distance_of_time_in_words(post.created_at, from_time) %> ago
  	</li> 
   <% end %>

 <% end %>

</ul>

app/views/boards/popular.html.erb
<h2> Popular threads </h2>

<ul>
 <% @popular.each do |post| %>

   <% if !post.title.nil? %>
   	<li>
   		<%= link_to '#'+post.title, post_path(post) %> | Comments ( <%= @commentAmountPerPost[post.id] %> )
  	</li> 
   <% end %>

 <% end %>

</ul>

app/views/boards/show.html.erb
<p class="topicDescription"><%= @board.description %></p>


<%= link_to "Trending", trending_board_path(@board), :method => :post,:class => "btn btn-white" %>

<%= link_to "New", new_thread_list_board_path(@board), :method => :post,:class => "btn btn-white" %>

<%= link_to "Popular", popular_board_path(@board), :method => :post,:class => "btn btn-white" %>

<%= link_to "Starred", starred_board_path(@board), :method => :post,:class => "btn btn-white" %>
<br>
<!--<%= link_to "<< Back to boards List", boards_path %>-->
	

<h3 style="padding:15px">Posts (<%= @board.posts.count %>)</h3>

<ul class="threadList">

<%= render :partial => 'post', :collection => @board.posts.reverse %>


</ul>

app/views/boards/starred.html.erb
<h2> Starred threads by <%= User.find(current_user.id).username %> </h2>

<ul>
 <% @starred.each do |post| %>

   <% if !post.title.nil? %>
   	<li>
   		<%= link_to '#'+post.title, post_path(post) %> | Starred ( <%= @starredAmountPerPost[post.id] %> ) times
  	</li> 
   <% end %>

 <% end %>

</ul>

app/views/boards/trending.html.erb
<h2> Trending threads </h2>

<ul>
 <% @trending.each do |post| %>

   <% if !post.title.nil? %>
   	<li>
   		<%= link_to '#'+post.title, post_path(post) %>
  	</li> 
   <% end %>

 <% end %>

</ul>