config/routes.rb
Fora::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :dashboard
  root :to => 'home#index'
  resources :boards
  resources :posts
  resources :after_register
  resources :follows
  resources :comments
  resources :posts do
    member do
      post :vote_up
      post :star
      post :unstar
      post :is_star
      post :stars_for
    end
  end
  resources :boards do
    member do
      post :follow_up
      post :follow_down
      post :is_following_up
      post :trending
      get  :trending
      post :new_thread_list
      get  :new_thread_list
      post :popular
      get  :popular
      post :starred
      get  :starred
    end
  end
  resources :replies
  resources :stars

end

app/models/post.rb
class Post < ActiveRecord::Base
  # attr_accessible :title, :body
  acts_as_voteable
  attr_accessible :author_name, :body, :title

  belongs_to :board
  has_many :comments
  has_many :stars
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    
    board_id = params[:post].delete(:board_id)

    @post = Post.new(params[:post])
    @post.board_id = board_id
    @post.user_id = current_user.id

    @post.save
    
    redirect_to board_path(@post.board)
  end

  def show
  	@post = Post.find(params[:id])
    @board = Board.find(@post.board_id)
    # ----
    # These are model (Board) functions. 
    @is_following_up = @board.is_following_up(@post.board_id, current_user.id)
    @board_members = @board.board_member_amount(@post.board_id)
  	# ----
    @comment = Comment.new
    @comment.post_id = @post.id
    # ----
    @reply = Reply.new
    # ----
    @stars_for = Star.find(:all, :conditions => { :post_id => params[:id], :status => 1 }).count
    # ----
  end

  def vote_up
    begin
      current_user.vote_for(@post = Post.find(params[:id]))
      redirect_to :back
      flash[:sucess] = "You have voted successfully"
      #render :nothing => true, :status => 200
    rescue ActiveRecord::RecordInvalid
      #render :nothing => true, :status => 404
      redirect_to :back
      flash[:error] = "You have already voted for this one"
    end
  end



  def star
    @post = Post.find(params[:id])
    @found = Star.find(:all, :conditions => { :user_id => current_user.id, :post_id => params[:id] })
    if @found.any?
      if @found[0].status == 0
        #update star status to 1
        @found[0].status = 1
        @found[0].save
        flash[:message] = "Nice! You starred '#{@post.title}' again !"
      else
        flash[:message] = "You already starred '#{@post.title}'  !"
      end  
      redirect_to post_path(@post)
    else
      #create a new star
      @star = Star.new
      @star.user_id = current_user.id
      @star.post_id = params[:id]
      @star.status = 1
      @star.save
      flash[:message] = "Voila! You just starred '#{@post.title}' ;) !"
      redirect_to post_path(@post)
    end
  end


  def unstar
    #Star down 'will not' delete the 'follow', it will just change the status (from 1 to 0)
    @post = Post.find(params[:id])
    @found = Star.find(:all, :conditions => { :user_id => current_user.id, :post_id => params[:id] })
    if @found.any?
      @found[0].status = 0
      @found[0].save
      flash[:message] = "You just unstarred '#{@post.title}'  !"
      redirect_to post_path(@post)
    else
      flash[:message] = "Oops! You are have NOT starred '#{@post.title}' yet!"
      redirect_to post_path(@post)
    end
  end

  def is_star(params)
    @found = Star.find(:all, :conditions => { :user_id => current_user.id, :post_id => params, :status => 1 })
    if @found.any?
      true
    else
      false
    end
  end

  def stars_for(params)
    @found = Star.find(:all, :conditions => { :post_id => params, :status => 1 })
    if @found.any?
      @found.count
    else
      false
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
						  <div class="newReplyContent" style="display:none;">
    							<div class="newReplyBox" style="display:none;">
      								<%= render :partial => 'posts/reply_form', :locals => { :comment_id => comment.id } %>
      
    							</div>
  							</div>
						<li>
							<div class="commentTop">
								<ul>
									<li><a href="#"><%= User.find(comment.user_id).username %></a></li>
									<li><% from_time = Time.now %><%= distance_of_time_in_words(comment.created_at, from_time) %> ago</li>
									<li class="reply">
										<!--<a href="#">Reply</a>!-->
										<button id="newReplyBtn" class="reply">Reply</button>
									</li>

								</ul>
								<div class="clear"></div>
							</div>
							<div class="cont">
								<%= comment.body %>
							</div>

							<div class="comment">
								<ul>
									<%= render :partial => 'reply', :locals => { :comment_id => comment.id } %>


								</ul>
							</div>
							
							<!--<%= render :partial => 'reply_form', :locals => { :comment_id => comment.id } %> !-->
							
						</li>

app/views/posts/_comment_form.html.erb
<%= form_for @comment do |f| %>
  <%= f.hidden_field :post_id %>
  <p>
    <div class="postEditor">
       <%= f.text_area :body, :id => "markItUp2" %>
      <button class="btn floatR">Submit</button>      
    </div>    
  </p>
<% end %>


<script type="text/javascript">
$(function() {
  // Add markItUp! to your textarea in one line
  // $('textarea').markItUp( { Settings }, { OptionalExtraSettings } );
  $('#markItUp2').markItUp(myMarkdownSettings);



});
</script>

app/views/posts/_nestedreply.html.erb
		<% reply = Reply.where(:comment_id => comment_id, :parent_reply_id => parent_id) %>
		

	  	<% if reply[0].nil? || parent_id == 0 %>
	 


	  	<% else %>
	  		
	  		<% reply = Reply.find(reply[0].id) %>
	  		
						<li>
							<div class="commentTop">
								<ul>
									
									<li><a href="#"><%= User.find(reply.user_id).username %></a></li>
									<li><% from_time = Time.now %><%= distance_of_time_in_words(reply.created_at, from_time) %> ago</li>
									<li class="NestedReply"><a href="#">Reply</a></li>
								</ul>
								<div class="clear"></div>
							</div>
							<div class="cont">
								<%= reply.body %>
							</div>							
							
						</li>
			
	  	<% end %>

app/views/posts/_reply.html.erb
		<% reply = Reply.where(:comment_id => comment_id) %>
		<% loopCounter = 0; %>

		<% reply.each do |r| %>
			
	  		
	  		<% reply = Reply.find(r.id) %>
	  		<li>
							<div class="commentTop">
								<ul>

									<li><a href="#"><%= User.find(reply.user_id).username %></a></li>
									<li><% from_time = Time.now %><%= distance_of_time_in_words(reply.created_at, from_time) %> ago</li>
									<li class="NestedReply"><a href="#">Reply</a></li>
								</ul>
								<div class="clear"></div>
							</div>
							
							<%= reply.body %>
							

							<div class="reply">
								<ul>
									
									<%= render :partial => 'nestedreply', :locals => { :comment_id => comment_id, :parent_id => reply.parent_reply_id } %>

								</ul>
							</div>
							
							
							
						</li>


	  	<% end %>
	  	

app/views/posts/_reply_form.html.erb
<%= form_for @reply do |f| %>
  <%= f.hidden_field :comment_id, :value => comment_id %>

  
  <p>
    <br>
    ------------------------
    <br>
    >> Reply:
    <div class="postEditor">
       <%= f.text_area :body %>
      <button>Submit</button>      
    </div>    
  </p>
<% end %>

app/views/posts/_top_ten_post.html.erb
<ul>
	
 <% @postsListLast.each do |post| %>

  <li>
   <% board = Board.find(post.board_id) %>
   <% followingBoard = Follow.find(:all, :conditions => {:user_id => current_user.id, :board_id => board.id, 
   	:status => 1}) %>
   <% if !followingBoard[0].nil? %>
   	<%= link_to '@'+board.title, board_path(board) %> /  


   	<% if !post.title.nil? %>
   		<%= link_to post.title, post_path(post) %>
	<% end %>

	<br>
	<%= board_member_amount(post.board_id) %> Members
   	<br>
   <% end %> 
  </li> 

 <% end %>


</ul>

app/views/posts/show.html.erb
<!--<%= link_to "<< Back to posts List", boards_path %>-->

				<!-- thread detail -->
				<div class="threadDetail">
					<%= link_to(vote_up_post_path(@post), :method => :post, :class => "upVote") do %>
						&#9650;<br />
						<span class="upVoteBg"><%=@post.votes_for%></span>
					<% end %>

				
				


					<div style="margin-left:45px;">		

						<h3><%= @post.title %></h3>
						&nbsp;
						<%= link_to(star_post_path(@post), :method => :post, :class => "upVote") do %>
							&#9650;<br />
							<span class="upVoteBg"><%= @stars_for %></span>
						<% end %>

						<h5>Created by: <%= @post.author_name %></h5>
					</div>
					<div class="description">
						<%= @post.body %>
					</div>
				</div>



				<%= render 'comment_form' %>

				<div class="comment">
					<ul>
					<%= render :partial => 'comment', :collection => @post.comments %>


					</ul>
				</div>