config/routes.rb
Fora::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :dashboard
  root :to => 'home#index'
  resources :boards
  resources :posts
  resources :after_register
  resources :follows
  resources :comments
  resources :posts do
    member do
      post :vote_up
      post :star
      post :unstar
      post :is_star
      post :stars_for
    end
  end
  resources :boards do
    member do
      post :follow_up
      post :follow_down
      post :is_following_up
      post :trending
      get  :trending
      post :new_thread_list
      get  :new_thread_list
      post :popular
      get  :popular
      post :starred
      get  :starred
    end
  end
  resources :replies
  resources :stars

end

app/models/board.rb
class Board < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :posts
  belongs_to :user

 def is_following_up(params, currentUser)
  @found = Follow.find(:all, :conditions => { :user_id => currentUser, :board_id => params, :status => 1 })
   if @found.any?
    true
   else
    false
   end
 end


 def board_member_amount(params)
  @found = Follow.where(:board_id => params, :status => 1).count
 end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :body
  belongs_to :post
  has_many :replies
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user

  validates_uniqueness_of :user_id, :scope => [:user_id, :board_id]

  scope :find_all_followed_boards, :conditions => {:status => 1}

end

app/models/post.rb
class Post < ActiveRecord::Base
  # attr_accessible :title, :body
  acts_as_voteable
  attr_accessible :author_name, :body, :title

  belongs_to :board
  has_many :comments
  has_many :stars
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :body
  belongs_to :comment
end

app/models/star.rb
class Star < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :user_id, :scope => [:user_id, :post_id]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  include Gravtastic

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :username, :country
  # attr_accessible :title, :body

  gravtastic :email

  acts_as_voter
  has_many :follows
  has_many :stars
  
  has_many :boards
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, order("created_at DESC")

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
  		if user_signed_in?
    		redirect_to :controller=>'dashboard', :action => 'index'
  		end

	end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    
    board_id = params[:post].delete(:board_id)

    @post = Post.new(params[:post])
    @post.board_id = board_id
    @post.user_id = current_user.id

    @post.save
    
    redirect_to board_path(@post.board)
  end

  def show
  	@post = Post.find(params[:id])
    @board = Board.find(@post.board_id)
    # ----
    # These are model (Board) functions. 
    @is_following_up = @board.is_following_up(@post.board_id, current_user.id)
    @board_members = @board.board_member_amount(@post.board_id)
  	# ----
    @comment = Comment.new
    @comment.post_id = @post.id
    # ----
    @reply = Reply.new
    # ----
    @stars_for = Star.find(:all, :conditions => { :post_id => params[:id], :status => 1 }).count
    # ----
  end

  def vote_up
    begin
      current_user.vote_for(@post = Post.find(params[:id]))
      redirect_to :back
      flash[:sucess] = "You have voted successfully"
      #render :nothing => true, :status => 200
    rescue ActiveRecord::RecordInvalid
      #render :nothing => true, :status => 404
      redirect_to :back
      flash[:error] = "You have already voted for this one"
    end
  end



  def star
    @post = Post.find(params[:id])
    @found = Star.find(:all, :conditions => { :user_id => current_user.id, :post_id => params[:id] })
    if @found.any?
      if @found[0].status == 0
        #update star status to 1
        @found[0].status = 1
        @found[0].save
        flash[:message] = "Nice! You starred '#{@post.title}' again !"
      else
        flash[:message] = "You already starred '#{@post.title}'  !"
      end  
      redirect_to post_path(@post)
    else
      #create a new star
      @star = Star.new
      @star.user_id = current_user.id
      @star.post_id = params[:id]
      @star.status = 1
      @star.save
      flash[:message] = "Voila! You just starred '#{@post.title}' ;) !"
      redirect_to post_path(@post)
    end
  end


  def unstar
    #Star down 'will not' delete the 'follow', it will just change the status (from 1 to 0)
    @post = Post.find(params[:id])
    @found = Star.find(:all, :conditions => { :user_id => current_user.id, :post_id => params[:id] })
    if @found.any?
      @found[0].status = 0
      @found[0].save
      flash[:message] = "You just unstarred '#{@post.title}'  !"
      redirect_to post_path(@post)
    else
      flash[:message] = "Oops! You are have NOT starred '#{@post.title}' yet!"
      redirect_to post_path(@post)
    end
  end

  def is_star(params)
    @found = Star.find(:all, :conditions => { :user_id => current_user.id, :post_id => params, :status => 1 })
    if @found.any?
      true
    else
      false
    end
  end

  def stars_for(params)
    @found = Star.find(:all, :conditions => { :post_id => params, :status => 1 })
    if @found.any?
      @found.count
    else
      false
    end
  end

end

app/controllers/stars_controller.rb
class StarsController < ApplicationController

 def index
  @stars = Star.all
 end

 def show
  @star = Star.find(params[:id])
	
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end	

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/boards_helper.rb
module BoardsHelper

 def is_following_up(params)
  @found = Follow.find(:all, :conditions => { :user_id => current_user.id, :board_id => params, :status => 1 })
   if @found.any?
    true
   else
    false
   end
 end


 def board_member_amount(params)
  @found = Follow.where(:board_id => params, :status => 1).count
 end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fora</title>  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" type="text/css" href="/markitup/skins/simple/style.css">
  <link rel="stylesheet" type="text/css" href="/markitup/sets/default/style.css">
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="/markitup/jquery.markitup.js"></script>
  <script type="text/javascript" src="/markitup/sets/default/set.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <!-- logo -->
    <ul>
      <li class="logo"><a href="/"><img src="/assets/blank.gif" alt="Fora.io" height="50" /></a></li>
      <li class="createRoom"><%= link_to "Create Room ", new_board_path, :class=> 'btn btn-big' %></li>
      <li class="searchTopic"><input type="text" class="textInput" placeholder="Search topic by #hashtag" /></li>
    </ul>

    <nav>
      <ul>
        <li><a href="#">About</a></li>
        <li><a href="#">FAQ</a></li>
        <li><a href="#">Feedback</a></li>
      </ul>
    </nav>

  </header>


  <section class="leftSideBar">


    <% if user_signed_in? %>

    <!-- profile -->
    <div class="profile">
      <figure>
        <img src="<%= current_user.gravatar_url(:rating => 'R', :secure => true, :size =>48) %>" />
      </figure>
      <ul>
        <li><h5><%= current_user.username %></h5></li>
        <li><a href="#">My account</a></il>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      </ul>
    </div>
    <div class="clear"></div>

    <!-- dashboard/following -->
    <nav>
      <ul>
        <li class="dashboard"><a href="/dashboard">Dashboard</a></li>
        <li><h5>Following</h5>
          <!-- Following room list -->
          <%= render :partial => "boards/follow_board_list" %>
        </li>
        
      </ul>
    </nav>      
                
      <% else %>
    <div class="signin">
      <h5>Sign In</h5>
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
        <%= f.email_field :email, :class => "textInput", :placeholder => "E-mail" %>

        <%= f.password_field :password, :class => "textInput", :placeholder => "Password" %>

        <% if devise_mapping.rememberable? -%>
          <div style="font-size:12px;padding:5px 0 5px 0;line-height:20px;color:#739094;font-family:'MuseoSlab';">
            <%= f.check_box :remember_me %> <%= f.label :remember_me %> <br />
          </div>
        <% end -%>

        <%= f.submit "Sign in", :class => "btn btn-white" %>

        <p style="padding-top:5px;"><%= render "devise/shared/links" %> </p>

      <% end %>      
      <div class="clear" style="height:40px;"></div>

      <h5>Are you new?</h5>

      <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>

        <%= f.email_field :email, :class => "textInput", :placeholder => "E-mail" %>

        <%= f.password_field :password, :class => "textInput", :placeholder => "Password" %>

        <%= f.password_field :password_confirmation, :class => "textInput", :placeholder => "Confirm Password" %>

        <div><%= f.submit "Sign up", :class => "btn btn-white" %></div>
      <% end %>

    </div>

     
      <% end %>


  </section>

  <section class="rightFluid <% if controller?("dashboard") && action?("index", "show") %> dashboardBox<% end %>">

    <% if (controller?("boards") && action?("show")) || (controller?("boards") && action?("trending")) || (controller?("posts") && action?("show")) %>
    <div class="top">
      <!-- topic info -->
      
      <%= render :partial => "boards/topic_info" %>    


    </div>
    <div class="clear"></div>


    <div class="threadSideBar">
      <!-- right side bar -->
      <div class="rightSideBar">
        <div class="sideContent">
          <h4>Topic Suggestions</h4>
          <ul>
            <li><a href="#">#ios</a></li>
            <li><a href="#">#iphone</a></li>
            <li><a href="#">#ipad</a></li>
            <li><a href="#">#macbook</a></li>
          </ul>
        </div>
      </div>
    
      <!-- thread list -->
      <div class="content">
       
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>

      <%= yield %>
      </div>
    </div>



    <% else %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>

      <%= yield %>   
    <% end %>

  </section>      

<% if (controller?("boards") && action?("show")) || (controller?("posts") && action?("show")) %>

  <div class="newThreadContent" style="display:none;">
    <div class="newThreadBox" style="display:none;">
      <%= render :partial => 'boards/post_form' %>
    </div>
  </div>




<script type="text/javascript">
$(function() {
  // Add markItUp! to your textarea in one line
  // $('textarea').markItUp( { Settings }, { OptionalExtraSettings } );
  $('#markItUp').markItUp(myMarkdownSettings);



  // You can add content from anywhere in your page
  // $.markItUp( { Settings } );  
  $('.add').click(function() {
    $('#markItUp').markItUp('insert',
      {   openWith:'<opening tag>',
        closeWith:'<\/closing tag>',
        placeholder: "New content"
      }
    );
    return false;
  });
  
  // And you can add/remove markItUp! whenever you want
  // $(textarea).markItUpRemove();
  $('.toggle').click(function() {
    if ($("#markItUp .markItUpEditor").length === 1) {
      $("#markItUp").markItUp('remove');
      $("span", this).text("get markItUp! back");
    } else {
      $('#markItUp').markItUp(mySettings);
      $("span", this).text("remove markItUp!");
    }
    return false;
  });
});
</script>

<% end %>

</body>
</html>